//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.RedisCache
{
    public partial class RedisWeb
    {
        
        private string mId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public static Redis ToRedis(RedisWeb redis)
        {
            Redis result = new Redis();
            result.Id = redis.Id;
            return result;
        }
        
        public static RedisWeb ToRedisWeb(Redis redis)
        {
            RedisWeb result = new RedisWeb();
            result.Id = redis.Id;
            return result;
        }
    }

}
