//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Avanade.Amp.Core.AADApp
{
    public partial class AADAppWeb
    {      
        private string mId;      
        private Avanade.Amp.Core.AADApp.AADAppName mName;
        private string mClientId;        
        private string mAppIdUri;
        private string mDnsName;        
        private string mTrafficManagerUrl;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public Avanade.Amp.Core.AADApp.AADAppName Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string ClientId
        {
            get
            {
                return this.mClientId;
            }
            set
            {
                this.mClientId = value;
            }
        }
        
        public string AppIdUri
        {
            get
            {
                return this.mAppIdUri;
            }
            set
            {
                this.mAppIdUri = value;
            }
        }
        
        public string DnsName
        {
            get
            {
                return this.mDnsName;
            }
            set
            {
                this.mDnsName = value;
            }
        }
        
        public string TrafficManagerUrl
        {
            get
            {
                return this.mTrafficManagerUrl;
            }
            set
            {
                this.mTrafficManagerUrl = value;
            }
        }
        
        public static AADApp ToAADApp(AADAppWeb app)
        {
            AADApp result = new AADApp();
            result.Id = app.Id;
            result.Name = app.Name;
            result.ClientId = app.ClientId;
            result.AppIdUri = app.AppIdUri;
            result.DnsName = app.DnsName;
            result.TrafficManagerUrl = app.TrafficManagerUrl;
            return result;
        }
        
        public static AADAppWeb ToAADAppWeb(AADApp app)
        {
            AADAppWeb result = new AADAppWeb();
            result.Id = app.Id;
            result.Name = app.Name;
            result.ClientId = app.ClientId;
            result.AppIdUri = app.AppIdUri;
            result.DnsName = app.DnsName;
            result.TrafficManagerUrl = app.TrafficManagerUrl;
            return result;
        }
    }
}
