//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.SiteRule
{
    public partial class SiteRuleWeb
    {
        private string mId;
        
        private System.Nullable<bool> mAllowed;
        
        private System.Nullable<bool> mAuditRead;
        
        private System.Nullable<bool> mAdmin;
        
        private string mCoreSgId;
        
        private string mSiteId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public System.Nullable<bool> Allowed
        {
            get
            {
                return this.mAllowed;
            }
            set
            {
                this.mAllowed = value;
            }
        }
        
        public System.Nullable<bool> AuditRead
        {
            get
            {
                return this.mAuditRead;
            }
            set
            {
                this.mAuditRead = value;
            }
        }
        
        public System.Nullable<bool> Admin
        {
            get
            {
                return this.mAdmin;
            }
            set
            {
                this.mAdmin = value;
            }
        }
        
        public string CoreSgId
        {
            get
            {
                return this.mCoreSgId;
            }
            set
            {
                this.mCoreSgId = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public static SiteRule ToSiteRule(SiteRuleWeb siteRule)
        {
            SiteRule result = new SiteRule();
            result.Id = siteRule.Id;
            result.Allowed = siteRule.Allowed;
            result.AuditRead = siteRule.AuditRead;
            result.Admin = siteRule.Admin;
            result.CoreSgId = siteRule.CoreSgId;
            result.SiteId = siteRule.SiteId;
            return result;
        }
        
        public static SiteRuleWeb ToSiteRuleWeb(SiteRule siteRule)
        {
            SiteRuleWeb result = new SiteRuleWeb();
            result.Id = siteRule.Id;
            result.Allowed = siteRule.Allowed;
            result.AuditRead = siteRule.AuditRead;
            result.Admin = siteRule.Admin;
            result.CoreSgId = siteRule.CoreSgId;
            result.SiteId = siteRule.SiteId;
            return result;
        }
    }
}
