//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Logs
{
    public partial class ScriptExecutionLogWeb
    {
        
        private string mId;
        
        private string mUserIdentity;
        
        private System.DateTime mStartTimeUtc;
        
        private System.Nullable<System.DateTime> mEndTimeUtc;
        
        private string mAccountId;
        
        private string mAccountName;
        
        private string mSiteId;
        
        private string mSiteName;
        
        private string mData;
        
        private string mRemoteIpAddress;
        
        private string mConnectionId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string UserIdentity
        {
            get
            {
                return this.mUserIdentity;
            }
            set
            {
                this.mUserIdentity = value;
            }
        }
        
        public System.DateTime StartTimeUtc
        {
            get
            {
                return this.mStartTimeUtc;
            }
            set
            {
                this.mStartTimeUtc = value;
            }
        }
        
        public System.Nullable<System.DateTime> EndTimeUtc
        {
            get
            {
                return this.mEndTimeUtc;
            }
            set
            {
                this.mEndTimeUtc = value;
            }
        }
        
        public string AccountId
        {
            get
            {
                return this.mAccountId;
            }
            set
            {
                this.mAccountId = value;
            }
        }
        
        public string AccountName
        {
            get
            {
                return this.mAccountName;
            }
            set
            {
                this.mAccountName = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public string SiteName
        {
            get
            {
                return this.mSiteName;
            }
            set
            {
                this.mSiteName = value;
            }
        }
        
        public string Data
        {
            get
            {
                return this.mData;
            }
            set
            {
                this.mData = value;
            }
        }
        
        public string RemoteIpAddress
        {
            get
            {
                return this.mRemoteIpAddress;
            }
            set
            {
                this.mRemoteIpAddress = value;
            }
        }
        
        public string ConnectionId
        {
            get
            {
                return this.mConnectionId;
            }
            set
            {
                this.mConnectionId = value;
            }
        }
        
        public static ScriptExecutionLog ToScriptExecutionLog(ScriptExecutionLogWeb psrunner)
        {
            ScriptExecutionLog result = new ScriptExecutionLog();
            result.Id = psrunner.Id;
            result.UserIdentity = psrunner.UserIdentity;
            result.StartTimeUtc = psrunner.StartTimeUtc;
            result.EndTimeUtc = psrunner.EndTimeUtc;
            result.AccountId = psrunner.AccountId;
            result.AccountName = psrunner.AccountName;
            result.SiteId = psrunner.SiteId;
            result.SiteName = psrunner.SiteName;
            result.Data = psrunner.Data;
            result.RemoteIpAddress = psrunner.RemoteIpAddress;
            result.ConnectionId = psrunner.ConnectionId;
            return result;
        }
        
        public static ScriptExecutionLogWeb ToScriptExecutionLogWeb(ScriptExecutionLog psrunner)
        {
            ScriptExecutionLogWeb result = new ScriptExecutionLogWeb();
            result.Id = psrunner.Id;
            result.UserIdentity = psrunner.UserIdentity;
            result.StartTimeUtc = psrunner.StartTimeUtc;
            result.EndTimeUtc = psrunner.EndTimeUtc;
            result.AccountId = psrunner.AccountId;
            result.AccountName = psrunner.AccountName;
            result.SiteId = psrunner.SiteId;
            result.SiteName = psrunner.SiteName;
            result.Data = psrunner.Data;
            result.RemoteIpAddress = psrunner.RemoteIpAddress;
            result.ConnectionId = psrunner.ConnectionId;
            return result;
        }
    }
}
