//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Logs
{
    public partial class SecurityLogWeb
    {
        
        private string mId;
        
        private string mUserIdentity;
        
        private long mStartTime;
        
        private string mTarget;
        
        private bool mAllowed;
        
        private string mMethod;
        
        private int mStatusCode;
        
        private string mSource;
        
        private string mRemoteIpAddress;
        
        private string mCorrelationIdentity;
        
        private string mDetails;
        
        private System.Nullable<long> mDuration;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string UserIdentity
        {
            get
            {
                return this.mUserIdentity;
            }
            set
            {
                this.mUserIdentity = value;
            }
        }
        
        public long StartTime
        {
            get
            {
                return this.mStartTime;
            }
            set
            {
                this.mStartTime = value;
            }
        }
        
        public string Target
        {
            get
            {
                return this.mTarget;
            }
            set
            {
                this.mTarget = value;
            }
        }
        
        public bool Allowed
        {
            get
            {
                return this.mAllowed;
            }
            set
            {
                this.mAllowed = value;
            }
        }
        
        public string Method
        {
            get
            {
                return this.mMethod;
            }
            set
            {
                this.mMethod = value;
            }
        }
        
        public int StatusCode
        {
            get
            {
                return this.mStatusCode;
            }
            set
            {
                this.mStatusCode = value;
            }
        }
        
        public string Source
        {
            get
            {
                return this.mSource;
            }
            set
            {
                this.mSource = value;
            }
        }
        
        public string RemoteIpAddress
        {
            get
            {
                return this.mRemoteIpAddress;
            }
            set
            {
                this.mRemoteIpAddress = value;
            }
        }
        
        public string CorrelationIdentity
        {
            get
            {
                return this.mCorrelationIdentity;
            }
            set
            {
                this.mCorrelationIdentity = value;
            }
        }
        
        public string Details
        {
            get
            {
                return this.mDetails;
            }
            set
            {
                this.mDetails = value;
            }
        }
        
        public System.Nullable<long> Duration
        {
            get
            {
                return this.mDuration;
            }
            set
            {
                this.mDuration = value;
            }
        }
        
        public static SecurityLog ToSecurityLog(SecurityLogWeb security)
        {
            SecurityLog result = new SecurityLog();
            result.Id = security.Id;
            result.UserIdentity = security.UserIdentity;
            result.StartTime = security.StartTime;
            result.Target = security.Target;
            result.Allowed = security.Allowed;
            result.Method = security.Method;
            result.StatusCode = security.StatusCode;
            result.Source = security.Source;
            result.RemoteIpAddress = security.RemoteIpAddress;
            result.CorrelationIdentity = security.CorrelationIdentity;
            result.Details = security.Details;
            result.Duration = security.Duration;
            return result;
        }
        
        public static SecurityLogWeb ToSecurityLogWeb(SecurityLog security)
        {
            SecurityLogWeb result = new SecurityLogWeb();
            result.Id = security.Id;
            result.UserIdentity = security.UserIdentity;
            result.StartTime = security.StartTime;
            result.Target = security.Target;
            result.Allowed = security.Allowed;
            result.Method = security.Method;
            result.StatusCode = security.StatusCode;
            result.Source = security.Source;
            result.RemoteIpAddress = security.RemoteIpAddress;
            result.CorrelationIdentity = security.CorrelationIdentity;
            result.Details = security.Details;
            result.Duration = security.Duration;
            return result;
        }
    }
}
