//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core
{
    public partial class VaultCredentialWeb
    {
        
        private string mId;
        
        private string mName;
        
        private string mDescription;
        
        private string mTenant;
        
        private string mSiteId;
        
        private string[] mTargetTypes;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Tenant
        {
            get
            {
                return this.mTenant;
            }
            set
            {
                this.mTenant = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public string[] TargetTypes
        {
            get
            {
                return this.mTargetTypes;
            }
            set
            {
                this.mTargetTypes = value;
            }
        }
        
        public static VaultCredential ToVaultCredential(VaultCredentialWeb credential)
        {
            VaultCredential result = new VaultCredential();
            result.Id = credential.Id;
            result.Name = credential.Name;
            result.Description = credential.Description;
            result.Tenant = credential.Tenant;
            result.SiteId = credential.SiteId;
            result.TargetTypes = credential.TargetTypes;
            return result;
        }
        
        public static VaultCredentialWeb ToVaultCredentialWeb(VaultCredential credential)
        {
            VaultCredentialWeb result = new VaultCredentialWeb();
            result.Id = credential.Id;
            result.Name = credential.Name;
            result.Description = credential.Description;
            result.Tenant = credential.Tenant;
            result.SiteId = credential.SiteId;
            result.TargetTypes = credential.TargetTypes;
            return result;
        }
    }
}
