//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Http;
using System.Net.Http.Headers;


namespace Avanade.Amp.Core
{
    public partial class VaultSecretWeb
    {
        
        private string mId;
        
        private string mName;
        
        private string mSiteId;
        
        private string mCredentialId;
        
        private string mTenant;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public string CredentialId
        {
            get
            {
                return this.mCredentialId;
            }
            set
            {
                this.mCredentialId = value;
            }
        }
        
        public string Tenant
        {
            get
            {
                return this.mTenant;
            }
            set
            {
                this.mTenant = value;
            }
        }
        
        public static VaultSecret ToVaultSecret(VaultSecretWeb secret)
        {
            VaultSecret result = new VaultSecret();
            result.Id = secret.Id;
            result.Name = secret.Name;
            result.SiteId = secret.SiteId;
            result.CredentialId = secret.CredentialId;
            result.Tenant = secret.Tenant;
            return result;
        }
        
        public static VaultSecretWeb ToVaultSecretWeb(VaultSecret secret)
        {
            VaultSecretWeb result = new VaultSecretWeb();
            result.Id = secret.Id;
            result.Name = secret.Name;
            result.SiteId = secret.SiteId;
            result.CredentialId = secret.CredentialId;
            result.Tenant = secret.Tenant;
            return result;
        }
    }
}
