//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Telemetry
{
    public partial class PingTelemetryWeb
    {
        private string mId;
        
        private string mRdpTelemetryId;
        
        private int mBatchNumber;
        
        private int mNumberOfPings;
        
        private float mAverageRoundtrip;
        
        private float mMaxRoundtrip;
        
        private float mMinRoundtrip;
        
        private string mData;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string RdpTelemetryId
        {
            get
            {
                return this.mRdpTelemetryId;
            }
            set
            {
                this.mRdpTelemetryId = value;
            }
        }
        
        public int BatchNumber
        {
            get
            {
                return this.mBatchNumber;
            }
            set
            {
                this.mBatchNumber = value;
            }
        }
        
        public int NumberOfPings
        {
            get
            {
                return this.mNumberOfPings;
            }
            set
            {
                this.mNumberOfPings = value;
            }
        }
        
        public float AverageRoundtrip
        {
            get
            {
                return this.mAverageRoundtrip;
            }
            set
            {
                this.mAverageRoundtrip = value;
            }
        }
        
        public float MaxRoundtrip
        {
            get
            {
                return this.mMaxRoundtrip;
            }
            set
            {
                this.mMaxRoundtrip = value;
            }
        }
        
        public float MinRoundtrip
        {
            get
            {
                return this.mMinRoundtrip;
            }
            set
            {
                this.mMinRoundtrip = value;
            }
        }
        
        public string Data
        {
            get
            {
                return this.mData;
            }
            set
            {
                this.mData = value;
            }
        }
        
        public static PingTelemetry ToPingTelemetry(PingTelemetryWeb ping)
        {
            PingTelemetry result = new PingTelemetry();
            result.Id = ping.Id;
            result.RdpTelemetryId = ping.RdpTelemetryId;
            result.BatchNumber = ping.BatchNumber;
            result.NumberOfPings = ping.NumberOfPings;
            result.AverageRoundtrip = ping.AverageRoundtrip;
            result.MaxRoundtrip = ping.MaxRoundtrip;
            result.MinRoundtrip = ping.MinRoundtrip;
            result.Data = ping.Data;
            return result;
        }
        
        public static PingTelemetryWeb ToPingTelemetryWeb(PingTelemetry ping)
        {
            PingTelemetryWeb result = new PingTelemetryWeb();
            result.Id = ping.Id;
            result.RdpTelemetryId = ping.RdpTelemetryId;
            result.BatchNumber = ping.BatchNumber;
            result.NumberOfPings = ping.NumberOfPings;
            result.AverageRoundtrip = ping.AverageRoundtrip;
            result.MaxRoundtrip = ping.MaxRoundtrip;
            result.MinRoundtrip = ping.MinRoundtrip;
            result.Data = ping.Data;
            return result;
        }
    }
}
