//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Script
{
    public partial class ScriptWeb
    {
        private string mId;
        
        private string mName;
        
        private string mDescription;
        
        private string mText;
        
        private System.Collections.Generic.IEnumerable<string> mCategories;
        
        private System.Collections.Generic.IEnumerable<ScriptParameter> mParameters;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Text
        {
            get
            {
                return this.mText;
            }
            set
            {
                this.mText = value;
            }
        }
        
        public System.Collections.Generic.IEnumerable<string> Categories
        {
            get
            {
                return this.mCategories;
            }
            set
            {
                this.mCategories = value;
            }
        }
        
        public System.Collections.Generic.IEnumerable<ScriptParameter> Parameters
        {
            get
            {
                return this.mParameters;
            }
            set
            {
                this.mParameters = value;
            }
        }
        
        public static Script ToScript(ScriptWeb script)
        {
            Script result = new Script();
            result.Id = script.Id;
            result.Name = script.Name;
            result.Description = script.Description;
            result.Text = script.Text;
            result.Categories = script.Categories;
            result.Parameters = script.Parameters;
            return result;
        }
        
        public static ScriptWeb ToScriptWeb(Script script)
        {
            ScriptWeb result = new ScriptWeb();
            result.Id = script.Id;
            result.Name = script.Name;
            result.Description = script.Description;
            result.Text = script.Text;
            result.Categories = script.Categories;
            result.Parameters = script.Parameters;
            return result;
        }
    }
}
