//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Directory
{
    public partial class DirectoryWeb
    {  
        private string mIdentity;       
        private string mName;
        
        public string Identity
        {
            get
            {
                return this.mIdentity;
            }
            set
            {
                this.mIdentity = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public static Directory ToDirectory(DirectoryWeb dir)
        {
            Directory result = new Directory();
            result.Identity = dir.Identity;
            result.Name = dir.Name;
            return result;
        }
        
        public static DirectoryWeb ToDirectoryWeb(Directory dir)
        {
            DirectoryWeb result = new DirectoryWeb();
            result.Identity = dir.Identity;
            result.Name = dir.Name;
            return result;
        }
    }
}
