//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.CoreSetting
{
    public partial class CoreSettingWeb
    {
        private string mId;
        
        private bool mValidateReferenceTicket;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public bool ValidateReferenceTicket
        {
            get
            {
                return this.mValidateReferenceTicket;
            }
            set
            {
                this.mValidateReferenceTicket = value;
            }
        }
        
        public static CoreSetting ToCoreSetting(CoreSettingWeb setting)
        {
            CoreSetting result = new CoreSetting();
            result.Id = setting.Id;
            result.ValidateReferenceTicket = setting.ValidateReferenceTicket;
            return result;
        }
        
        public static CoreSettingWeb ToCoreSettingWeb(CoreSetting setting)
        {
            CoreSettingWeb result = new CoreSettingWeb();
            result.Id = setting.Id;
            result.ValidateReferenceTicket = setting.ValidateReferenceTicket;
            return result;
        }
    }
}
