//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Rdp
{
    public partial class RdpEncodingLogWeb
    {
        
        private string mId;
        
        private string mSiteId;
        
        private string mConnectionId;
        
        private double mProgress;
        
        private System.Nullable<System.DateTime> mLatestProgressUpdate;
        
        private bool mRequestedCancel;
        
        private string mStatus;
        
        private string mFormat;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public string ConnectionId
        {
            get
            {
                return this.mConnectionId;
            }
            set
            {
                this.mConnectionId = value;
            }
        }
        
        public double Progress
        {
            get
            {
                return this.mProgress;
            }
            set
            {
                this.mProgress = value;
            }
        }
        
        public System.Nullable<System.DateTime> LatestProgressUpdate
        {
            get
            {
                return this.mLatestProgressUpdate;
            }
            set
            {
                this.mLatestProgressUpdate = value;
            }
        }
        
        public bool RequestedCancel
        {
            get
            {
                return this.mRequestedCancel;
            }
            set
            {
                this.mRequestedCancel = value;
            }
        }
        
        public string Status
        {
            get
            {
                return this.mStatus;
            }
            set
            {
                this.mStatus = value;
            }
        }
        
        public string Format
        {
            get
            {
                return this.mFormat;
            }
            set
            {
                this.mFormat = value;
            }
        }
        
        public static RdpEncodingLog ToRdpEncodingLog(RdpEncodingLogWeb rdpEncodingLog)
        {
            RdpEncodingLog result = new RdpEncodingLog();
            result.Id = rdpEncodingLog.Id;
            result.SiteId = rdpEncodingLog.SiteId;
            result.ConnectionId = rdpEncodingLog.ConnectionId;
            result.Progress = rdpEncodingLog.Progress;
            result.LatestProgressUpdate = rdpEncodingLog.LatestProgressUpdate;
            result.RequestedCancel = rdpEncodingLog.RequestedCancel;
            result.Status = rdpEncodingLog.Status;
            result.Format = rdpEncodingLog.Format;
            return result;
        }
        
        public static RdpEncodingLogWeb ToRdpEncodingLogWeb(RdpEncodingLog rdpEncodingLog)
        {
            RdpEncodingLogWeb result = new RdpEncodingLogWeb();
            result.Id = rdpEncodingLog.Id;
            result.SiteId = rdpEncodingLog.SiteId;
            result.ConnectionId = rdpEncodingLog.ConnectionId;
            result.Progress = rdpEncodingLog.Progress;
            result.LatestProgressUpdate = rdpEncodingLog.LatestProgressUpdate;
            result.RequestedCancel = rdpEncodingLog.RequestedCancel;
            result.Status = rdpEncodingLog.Status;
            result.Format = rdpEncodingLog.Format;
            return result;
        }
    }
}
