//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Rdp
{
    public partial class RdpSessionWeb
    {
        
        private string mId;
        
        private string mConnectionIdentity;
        
        private System.DateTime mStartTime;
        
        private string mUserIdentity;
        
        private string mCredentialIdentity;
        
        private string mTargetId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string ConnectionIdentity
        {
            get
            {
                return this.mConnectionIdentity;
            }
            set
            {
                this.mConnectionIdentity = value;
            }
        }
        
        public System.DateTime StartTime
        {
            get
            {
                return this.mStartTime;
            }
            set
            {
                this.mStartTime = value;
            }
        }
        
        public string UserIdentity
        {
            get
            {
                return this.mUserIdentity;
            }
            set
            {
                this.mUserIdentity = value;
            }
        }
        
        public string CredentialIdentity
        {
            get
            {
                return this.mCredentialIdentity;
            }
            set
            {
                this.mCredentialIdentity = value;
            }
        }
        
        public string TargetId
        {
            get
            {
                return this.mTargetId;
            }
            set
            {
                this.mTargetId = value;
            }
        }
        
        public static RdpSession ToRdpSession(RdpSessionWeb rdpSession)
        {
            RdpSession result = new RdpSession();
            result.Id = rdpSession.Id;
            result.ConnectionIdentity = rdpSession.ConnectionIdentity;
            result.StartTime = rdpSession.StartTime;
            result.UserIdentity = rdpSession.UserIdentity;
            result.CredentialIdentity = rdpSession.CredentialIdentity;
            result.TargetId = rdpSession.TargetId;
            return result;
        }
        
        public static RdpSessionWeb ToRdpSessionWeb(RdpSession rdpSession)
        {
            RdpSessionWeb result = new RdpSessionWeb();
            result.Id = rdpSession.Id;
            result.ConnectionIdentity = rdpSession.ConnectionIdentity;
            result.StartTime = rdpSession.StartTime;
            result.UserIdentity = rdpSession.UserIdentity;
            result.CredentialIdentity = rdpSession.CredentialIdentity;
            result.TargetId = rdpSession.TargetId;
            return result;
        }
    }
}
