//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.TokenRecord
{
    public partial class TokenRecordWeb
    {
        
        private string mId;
        
        private byte[] mCacheBits;
        
        private long mLastWrite;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public byte[] CacheBits
        {
            get
            {
                return this.mCacheBits;
            }
            set
            {
                this.mCacheBits = value;
            }
        }
        
        public long LastWrite
        {
            get
            {
                return this.mLastWrite;
            }
            set
            {
                this.mLastWrite = value;
            }
        }
        
        public static TokenRecord ToTokenRecord(TokenRecordWeb tokenRecord)
        {
            TokenRecord result = new TokenRecord();
            result.Id = tokenRecord.Id;
            result.CacheBits = tokenRecord.CacheBits;
            result.LastWrite = tokenRecord.LastWrite;
            return result;
        }
        
        public static TokenRecordWeb ToTokenRecordWeb(TokenRecord tokenRecord)
        {
            TokenRecordWeb result = new TokenRecordWeb();
            result.Id = tokenRecord.Id;
            result.CacheBits = tokenRecord.CacheBits;
            result.LastWrite = tokenRecord.LastWrite;
            return result;
        }
    }
}
