//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Account
{
    public partial class AccountWeb
    {    
        private string mId;
        
        private string mName;
        
        private string mShortName;
        
        private string mExternalIdentity;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string ShortName
        {
            get
            {
                return this.mShortName;
            }
            set
            {
                this.mShortName = value;
            }
        }
        
        public string ExternalIdentity
        {
            get
            {
                return this.mExternalIdentity;
            }
            set
            {
                this.mExternalIdentity = value;
            }
        }
        
        public static Account ToAccount(AccountWeb account)
        {
            Account result = new Account();
            result.Id = account.Id;
            result.Name = account.Name;
            result.ShortName = account.ShortName;
            result.ExternalIdentity = account.ExternalIdentity;
            return result;
        }
        
        public static AccountWeb ToAccountWeb(Account account)
        {
            AccountWeb result = new AccountWeb();
            result.Id = account.Id;
            result.Name = account.Name;
            result.ShortName = account.ShortName;
            result.ExternalIdentity = account.ExternalIdentity;
            return result;
        }
    }
}
