//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Kibana
{
    
    
    public partial class KibanaConfigWeb
    {
        
        private string mId;
        
        private string mElasticIdentity;
        
        private string mSourceJson;
        
        private string mBundleId;
        
        private System.Nullable<System.DateTime> mCreatedDate;
        
        private System.Nullable<System.DateTime> mLastModifiedDate;
        
        private string mLastModifiedBy;
        
        private string mCreatedBy;
        
        private byte[] mRowVersion;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string ElasticIdentity
        {
            get
            {
                return this.mElasticIdentity;
            }
            set
            {
                this.mElasticIdentity = value;
            }
        }
        
        public string SourceJson
        {
            get
            {
                return this.mSourceJson;
            }
            set
            {
                this.mSourceJson = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.mCreatedDate;
            }
            set
            {
                this.mCreatedDate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastModifiedDate
        {
            get
            {
                return this.mLastModifiedDate;
            }
            set
            {
                this.mLastModifiedDate = value;
            }
        }
        
        public string LastModifiedBy
        {
            get
            {
                return this.mLastModifiedBy;
            }
            set
            {
                this.mLastModifiedBy = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.mCreatedBy;
            }
            set
            {
                this.mCreatedBy = value;
            }
        }
        
        public byte[] RowVersion
        {
            get
            {
                return this.mRowVersion;
            }
            set
            {
                this.mRowVersion = value;
            }
        }
        
        public static KibanaConfig ToKibanaConfig(KibanaConfigWeb kibanaConfig)
        {
            KibanaConfig result = new KibanaConfig();
            result.Id = kibanaConfig.Id;
            result.ElasticIdentity = kibanaConfig.ElasticIdentity;
            result.SourceJson = kibanaConfig.SourceJson;
            result.BundleId = kibanaConfig.BundleId;
            result.CreatedDate = kibanaConfig.CreatedDate;
            result.LastModifiedDate = kibanaConfig.LastModifiedDate;
            result.LastModifiedBy = kibanaConfig.LastModifiedBy;
            result.CreatedBy = kibanaConfig.CreatedBy;
            result.RowVersion = kibanaConfig.RowVersion;
            return result;
        }
        
        public static KibanaConfigWeb ToKibanaConfigWeb(KibanaConfig kibanaConfig)
        {
            KibanaConfigWeb result = new KibanaConfigWeb();
            result.Id = kibanaConfig.Id;
            result.ElasticIdentity = kibanaConfig.ElasticIdentity;
            result.SourceJson = kibanaConfig.SourceJson;
            result.BundleId = kibanaConfig.BundleId;
            result.CreatedDate = kibanaConfig.CreatedDate;
            result.LastModifiedDate = kibanaConfig.LastModifiedDate;
            result.LastModifiedBy = kibanaConfig.LastModifiedBy;
            result.CreatedBy = kibanaConfig.CreatedBy;
            result.RowVersion = kibanaConfig.RowVersion;
            return result;
        }
    }
}
