//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Subscription
{
    public partial class SubscriptionWeb
    {
        
        private string mId;
        
        private string mExternalIdentity;
        
        private string mTenantId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string ExternalIdentity
        {
            get
            {
                return this.mExternalIdentity;
            }
            set
            {
                this.mExternalIdentity = value;
            }
        }
        
        public string TenantId
        {
            get
            {
                return this.mTenantId;
            }
            set
            {
                this.mTenantId = value;
            }
        }
        
        public static Subscription ToSubscription(SubscriptionWeb subscription)
        {
            Subscription result = new Subscription();
            result.Id = subscription.Id;
            result.ExternalIdentity = subscription.ExternalIdentity;
            result.TenantId = subscription.TenantId;
            return result;
        }
        
        public static SubscriptionWeb ToSubscriptionWeb(Subscription subscription)
        {
            SubscriptionWeb result = new SubscriptionWeb();
            result.Id = subscription.Id;
            result.ExternalIdentity = subscription.ExternalIdentity;
            result.TenantId = subscription.TenantId;
            return result;
        }
    }
}
