//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.UserSetting
{
    public partial class UserSettingWeb
    {
        
        private string mId;
        
        private string mKey;
        
        private string mValue;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Key
        {
            get
            {
                return this.mKey;
            }
            set
            {
                this.mKey = value;
            }
        }
        
        public string Value
        {
            get
            {
                return this.mValue;
            }
            set
            {
                this.mValue = value;
            }
        }
        
        public static UserSetting ToUserSetting(UserSettingWeb userSetting)
        {
            UserSetting result = new UserSetting();
            result.Id = userSetting.Id;
            result.Key = userSetting.Key;
            result.Value = userSetting.Value;
            return result;
        }
        
        public static UserSettingWeb ToUserSettingWeb(UserSetting userSetting)
        {
            UserSettingWeb result = new UserSettingWeb();
            result.Id = userSetting.Id;
            result.Key = userSetting.Key;
            result.Value = userSetting.Value;
            return result;
        }
    }
}
