//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;


namespace Avanade.Amp.Core.Role
{
    public partial class CoreSgRoleWeb
    {
        
        private string mId;
        
        private string mRole;
        
        private string mCoreSgId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Role
        {
            get
            {
                return this.mRole;
            }
            set
            {
                this.mRole = value;
            }
        }
        
        public string CoreSgId
        {
            get
            {
                return this.mCoreSgId;
            }
            set
            {
                this.mCoreSgId = value;
            }
        }
        
        public static CoreSgRole ToCoreSgRole(CoreSgRoleWeb coreSgRole)
        {
            CoreSgRole result = new CoreSgRole();
            result.Id = coreSgRole.Id;
            result.Role = coreSgRole.Role;
            result.CoreSgId = coreSgRole.CoreSgId;
            return result;
        }
        
        public static CoreSgRoleWeb ToCoreSgRoleWeb(CoreSgRole coreSgRole)
        {
            CoreSgRoleWeb result = new CoreSgRoleWeb();
            result.Id = coreSgRole.Id;
            result.Role = coreSgRole.Role;
            result.CoreSgId = coreSgRole.CoreSgId;
            return result;
        }
    }
}
