//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;

using System.Net.Http.Headers;
using System.Threading.Tasks;



namespace Avanade.Amp.Core.CoreSg
{
    
    
    public partial class CoreSgWeb
    {
        
        private string mId;
        
        private string mName;
        
        private string mExternalIdentity;
        
        private string mTenantId;
        
        private System.Nullable<bool> mCanCreate;
        
        private System.Nullable<bool> mCanDelete;
        
        private System.Nullable<bool> mEditSiteAccess;
        
        private System.Nullable<bool> mAdmin;
        
        private System.Nullable<bool> mAudit;
        
        private System.Nullable<bool> mOpsAdmin;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string ExternalIdentity
        {
            get
            {
                return this.mExternalIdentity;
            }
            set
            {
                this.mExternalIdentity = value;
            }
        }
        
        public string TenantId
        {
            get
            {
                return this.mTenantId;
            }
            set
            {
                this.mTenantId = value;
            }
        }
        
        public System.Nullable<bool> CanCreate
        {
            get
            {
                return this.mCanCreate;
            }
            set
            {
                this.mCanCreate = value;
            }
        }
        
        public System.Nullable<bool> CanDelete
        {
            get
            {
                return this.mCanDelete;
            }
            set
            {
                this.mCanDelete = value;
            }
        }
        
        public System.Nullable<bool> EditSiteAccess
        {
            get
            {
                return this.mEditSiteAccess;
            }
            set
            {
                this.mEditSiteAccess = value;
            }
        }
        
        public System.Nullable<bool> Admin
        {
            get
            {
                return this.mAdmin;
            }
            set
            {
                this.mAdmin = value;
            }
        }
        
        public System.Nullable<bool> Audit
        {
            get
            {
                return this.mAudit;
            }
            set
            {
                this.mAudit = value;
            }
        }
        
        public System.Nullable<bool> OpsAdmin
        {
            get
            {
                return this.mOpsAdmin;
            }
            set
            {
                this.mOpsAdmin = value;
            }
        }
        
        public static CoreSg ToCoreSg(CoreSgWeb coreSg)
        {
            CoreSg result = new CoreSg();
            result.Id = coreSg.Id;
            result.Name = coreSg.Name;
            result.ExternalIdentity = coreSg.ExternalIdentity;
            result.TenantId = coreSg.TenantId;
            result.CanCreate = coreSg.CanCreate;
            result.CanDelete = coreSg.CanDelete;
            result.EditSiteAccess = coreSg.EditSiteAccess;
            result.Admin = coreSg.Admin;
            result.Audit = coreSg.Audit;
            result.OpsAdmin = coreSg.OpsAdmin;
            return result;
        }
        
        public static CoreSgWeb ToCoreSgWeb(CoreSg coreSg)
        {
            CoreSgWeb result = new CoreSgWeb();
            result.Id = coreSg.Id;
            result.Name = coreSg.Name;
            result.ExternalIdentity = coreSg.ExternalIdentity;
            result.TenantId = coreSg.TenantId;
            result.CanCreate = coreSg.CanCreate;
            result.CanDelete = coreSg.CanDelete;
            result.EditSiteAccess = coreSg.EditSiteAccess;
            result.Admin = coreSg.Admin;
            result.Audit = coreSg.Audit;
            result.OpsAdmin = coreSg.OpsAdmin;
            return result;
        }
    }
}
