//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Cluster
{
    public partial class ClusterWeb
    {
        private string mId;
        
        private string mName;
        
        private string mAzureRegion;
        
        private string mUri;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string AzureRegion
        {
            get
            {
                return this.mAzureRegion;
            }
            set
            {
                this.mAzureRegion = value;
            }
        }
        
        public string Uri
        {
            get
            {
                return this.mUri;
            }
            set
            {
                this.mUri = value;
            }
        }
        
        public static Cluster ToCluster(ClusterWeb cluster)
        {
            Cluster result = new Cluster();
            result.Id = cluster.Id;
            result.Name = cluster.Name;
            result.AzureRegion = cluster.AzureRegion;
            result.Uri = cluster.Uri;
            return result;
        }
        
        public static ClusterWeb ToClusterWeb(Cluster cluster)
        {
            ClusterWeb result = new ClusterWeb();
            result.Id = cluster.Id;
            result.Name = cluster.Name;
            result.AzureRegion = cluster.AzureRegion;
            result.Uri = cluster.Uri;
            return result;
        }
    }
}
