//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.TypeBundleMap
{
    public partial class TypeBundleMapWeb
    {
        
        private string mId;
        
        private string mType;
        
        private string mBundleId;
        
        private string mSiteId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Type
        {
            get
            {
                return this.mType;
            }
            set
            {
                this.mType = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public static TypeBundleMap ToTypeBundleMap(TypeBundleMapWeb typeBundleMap)
        {
            TypeBundleMap result = new TypeBundleMap();
            result.Id = typeBundleMap.Id;
            result.Type = typeBundleMap.Type;
            result.BundleId = typeBundleMap.BundleId;
            result.SiteId = typeBundleMap.SiteId;
            return result;
        }
        
        public static TypeBundleMapWeb ToTypeBundleMapWeb(TypeBundleMap typeBundleMap)
        {
            TypeBundleMapWeb result = new TypeBundleMapWeb();
            result.Id = typeBundleMap.Id;
            result.Type = typeBundleMap.Type;
            result.BundleId = typeBundleMap.BundleId;
            result.SiteId = typeBundleMap.SiteId;
            return result;
        }
    }
}
