//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.ApiDefinition
{
    public partial class ApiDefinitionWeb
    {
        private string mId;
        
        private string mRelativePath;
        
        private string mMethod;
        
        private string mDocumentation;
        
        private System.Collections.Generic.List<Avanade.Amp.Core.ApiDefinition.ApiParameter> mParameters;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string RelativePath
        {
            get
            {
                return this.mRelativePath;
            }
            set
            {
                this.mRelativePath = value;
            }
        }
        
        public string Method
        {
            get
            {
                return this.mMethod;
            }
            set
            {
                this.mMethod = value;
            }
        }
        
        public string Documentation
        {
            get
            {
                return this.mDocumentation;
            }
            set
            {
                this.mDocumentation = value;
            }
        }
        
        public System.Collections.Generic.List<Avanade.Amp.Core.ApiDefinition.ApiParameter> Parameters
        {
            get
            {
                return this.mParameters;
            }
            set
            {
                this.mParameters = value;
            }
        }
        
        public static ApiDefinition ToApiDefinition(ApiDefinitionWeb api)
        {
            ApiDefinition result = new ApiDefinition();
            result.Id = api.Id;
            result.RelativePath = api.RelativePath;
            result.Method = api.Method;
            result.Documentation = api.Documentation;
            result.Parameters = api.Parameters;
            return result;
        }
        
        public static ApiDefinitionWeb ToApiDefinitionWeb(ApiDefinition api)
        {
            ApiDefinitionWeb result = new ApiDefinitionWeb();
            result.Id = api.Id;
            result.RelativePath = api.RelativePath;
            result.Method = api.Method;
            result.Documentation = api.Documentation;
            result.Parameters = api.Parameters;
            return result;
        }
    }
}
