//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Tenant
{
    public partial class TenantWeb
    {
        
        private string mId;
        
        private string mName;
        
        private string mExternalIdentity;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string ExternalIdentity
        {
            get
            {
                return this.mExternalIdentity;
            }
            set
            {
                this.mExternalIdentity = value;
            }
        }
        
        public static Tenant ToTenant(TenantWeb tenant)
        {
            Tenant result = new Tenant();
            result.Id = tenant.Id;
            result.Name = tenant.Name;
            result.ExternalIdentity = tenant.ExternalIdentity;
            return result;
        }
        
        public static TenantWeb ToTenantWeb(Tenant tenant)
        {
            TenantWeb result = new TenantWeb();
            result.Id = tenant.Id;
            result.Name = tenant.Name;
            result.ExternalIdentity = tenant.ExternalIdentity;
            return result;
        }
    }
}
