//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avanade.Amp.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apples.
        /// </summary>
        public static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueBerries.
        /// </summary>
        public static string Blueberries {
            get {
                return ResourceManager.GetString("Blueberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both in and out parameters should not be specified.
        /// </summary>
        public static string BothInOutParamsIllegal {
            get {
                return ResourceManager.GetString("BothInOutParamsIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string is not accepted.
        /// </summary>
        public static string EmptyStringIllegal {
            get {
                return ResourceManager.GetString("EmptyStringIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventArgs are required.
        /// </summary>
        public static string EventArgsRequired {
            get {
                return ResourceManager.GetString("EventArgsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both in and out parameters can not be NULL.
        /// </summary>
        public static string InOutParamCantBeNULL {
            get {
                return ResourceManager.GetString("InOutParamCantBeNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In parameter may not be specified.
        /// </summary>
        public static string InParamIllegal {
            get {
                return ResourceManager.GetString("InParamIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be between 0 and {0}.
        /// </summary>
        public static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lions.
        /// </summary>
        public static string Lions {
            get {
                return ResourceManager.GetString("Lions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My DropDown Combo.
        /// </summary>
        public static string MyDropDownCombo {
            get {
                return ResourceManager.GetString("MyDropDownCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dynamic Combo.
        /// </summary>
        public static string MyDynamicCombo {
            get {
                return ResourceManager.GetString("MyDynamicCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Index Combo.
        /// </summary>
        public static string MyIndexCombo {
            get {
                return ResourceManager.GetString("MyIndexCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My MRU Combo.
        /// </summary>
        public static string MyMRUCombo {
            get {
                return ResourceManager.GetString("MyMRUCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranges.
        /// </summary>
        public static string Oranges {
            get {
                return ResourceManager.GetString("Oranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out parameter can not be NULL.
        /// </summary>
        public static string OutParamRequired {
            get {
                return ResourceManager.GetString("OutParamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be either index or valid string in list.
        /// </summary>
        public static string ParamMustBeValidIndexOrStringInList {
            get {
                return ResourceManager.GetString("ParamMustBeValidIndexOrStringInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be valid string in list.
        /// </summary>
        public static string ParamNotValidStringInList {
            get {
                return ResourceManager.GetString("ParamNotValidStringInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pears.
        /// </summary>
        public static string Pears {
            get {
                return ResourceManager.GetString("Pears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strawberries.
        /// </summary>
        public static string Strawberries {
            get {
                return ResourceManager.GetString("Strawberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tigers.
        /// </summary>
        public static string Tigers {
            get {
                return ResourceManager.GetString("Tigers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Fit.
        /// </summary>
        public static string Zoom_to_Fit {
            get {
                return ResourceManager.GetString("Zoom_to_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom factor must be &gt; 0.
        /// </summary>
        public static string ZoomMustBeGTZero {
            get {
                return ResourceManager.GetString("ZoomMustBeGTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZoomToFit.
        /// </summary>
        public static string ZoomToFit {
            get {
                return ResourceManager.GetString("ZoomToFit", resourceCulture);
            }
        }
    }
}
