//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.SiteProxy
{
    public partial class SiteProxyMessageWeb
    {
        
        private string mId;
        
        private ProxyHttpMethod mMethod;
        
        private string mUri;
        
        private object mData;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public ProxyHttpMethod Method
        {
            get
            {
                return this.mMethod;
            }
            set
            {
                this.mMethod = value;
            }
        }
        
        public string Uri
        {
            get
            {
                return this.mUri;
            }
            set
            {
                this.mUri = value;
            }
        }
        
        public object Data
        {
            get
            {
                return this.mData;
            }
            set
            {
                this.mData = value;
            }
        }
        
        public static SiteProxyMessage ToSiteProxyMessage(SiteProxyMessageWeb site)
        {
            SiteProxyMessage result = new SiteProxyMessage();
            result.Id = site.Id;
            result.Method = site.Method;
            result.Uri = site.Uri;
            result.Data = site.Data;
            return result;
        }
        
        public static SiteProxyMessageWeb ToSiteProxyMessageWeb(SiteProxyMessage site)
        {
            SiteProxyMessageWeb result = new SiteProxyMessageWeb();
            result.Id = site.Id;
            result.Method = site.Method;
            result.Uri = site.Uri;
            result.Data = site.Data;
            return result;
        }
    }
}
