//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Monitoring
{
    public partial class BundleWeb
    {
        
        private string mId;
        
        private string mName;
        
        private string mDescription;
        
        private string mVersion;
        
        private System.Nullable<System.DateTime> mCreatedDate;
        
        private System.Nullable<System.DateTime> mLastModifiedDate;
        
        private string mLastModifiedBy;
        
        private string mCreatedBy;
        
        private byte[] mRowVersion;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Version
        {
            get
            {
                return this.mVersion;
            }
            set
            {
                this.mVersion = value;
            }
        }
        
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.mCreatedDate;
            }
            set
            {
                this.mCreatedDate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastModifiedDate
        {
            get
            {
                return this.mLastModifiedDate;
            }
            set
            {
                this.mLastModifiedDate = value;
            }
        }
        
        public string LastModifiedBy
        {
            get
            {
                return this.mLastModifiedBy;
            }
            set
            {
                this.mLastModifiedBy = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.mCreatedBy;
            }
            set
            {
                this.mCreatedBy = value;
            }
        }
        
        public byte[] RowVersion
        {
            get
            {
                return this.mRowVersion;
            }
            set
            {
                this.mRowVersion = value;
            }
        }
        
        public static Bundle ToBundle(BundleWeb bundle)
        {
            Bundle result = new Bundle();
            result.Id = bundle.Id;
            result.Name = bundle.Name;
            result.Description = bundle.Description;
            result.Version = bundle.Version;
            result.CreatedDate = bundle.CreatedDate;
            result.LastModifiedDate = bundle.LastModifiedDate;
            result.LastModifiedBy = bundle.LastModifiedBy;
            result.CreatedBy = bundle.CreatedBy;
            result.RowVersion = bundle.RowVersion;
            return result;
        }
        
        public static BundleWeb ToBundleWeb(Bundle bundle)
        {
            BundleWeb result = new BundleWeb();
            result.Id = bundle.Id;
            result.Name = bundle.Name;
            result.Description = bundle.Description;
            result.Version = bundle.Version;
            result.CreatedDate = bundle.CreatedDate;
            result.LastModifiedDate = bundle.LastModifiedDate;
            result.LastModifiedBy = bundle.LastModifiedBy;
            result.CreatedBy = bundle.CreatedBy;
            result.RowVersion = bundle.RowVersion;
            return result;
        }
    }

}
