//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;

using System.Net.Http.Headers;
using System.Threading.Tasks;



namespace Avanade.Amp.Core.Monitoring
{
    
    
    public partial class PercolatorWeb
    {
        
        private string mId;
        
        private string mBundleId;
        
        private string mName;
        
        private string mDescription;
        
        private string mType;
        
        private System.Nullable<int> mSeverity;
        
        private string mQuery;
        
        private string mIssueType;
        
        private string mResource;
        
        private string mResponse;
        
        private string mResponder;
        
        private string mVisualization;
        
        private bool mMatchAll;
        
        private string mImplementationNotes;
        
        private System.Nullable<System.DateTime> mCreatedDate;
        
        private System.Nullable<System.DateTime> mLastModifiedDate;
        
        private string mLastModifiedBy;
        
        private string mCreatedBy;
        
        private byte[] mRowVersion;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Type
        {
            get
            {
                return this.mType;
            }
            set
            {
                this.mType = value;
            }
        }
        
        public System.Nullable<int> Severity
        {
            get
            {
                return this.mSeverity;
            }
            set
            {
                this.mSeverity = value;
            }
        }
        
        public string Query
        {
            get
            {
                return this.mQuery;
            }
            set
            {
                this.mQuery = value;
            }
        }
        
        public string IssueType
        {
            get
            {
                return this.mIssueType;
            }
            set
            {
                this.mIssueType = value;
            }
        }
        
        public string Resource
        {
            get
            {
                return this.mResource;
            }
            set
            {
                this.mResource = value;
            }
        }
        
        public string Response
        {
            get
            {
                return this.mResponse;
            }
            set
            {
                this.mResponse = value;
            }
        }
        
        public string Responder
        {
            get
            {
                return this.mResponder;
            }
            set
            {
                this.mResponder = value;
            }
        }
        
        public string Visualization
        {
            get
            {
                return this.mVisualization;
            }
            set
            {
                this.mVisualization = value;
            }
        }
        
        public bool MatchAll
        {
            get
            {
                return this.mMatchAll;
            }
            set
            {
                this.mMatchAll = value;
            }
        }
        
        public string ImplementationNotes
        {
            get
            {
                return this.mImplementationNotes;
            }
            set
            {
                this.mImplementationNotes = value;
            }
        }
        
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.mCreatedDate;
            }
            set
            {
                this.mCreatedDate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastModifiedDate
        {
            get
            {
                return this.mLastModifiedDate;
            }
            set
            {
                this.mLastModifiedDate = value;
            }
        }
        
        public string LastModifiedBy
        {
            get
            {
                return this.mLastModifiedBy;
            }
            set
            {
                this.mLastModifiedBy = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.mCreatedBy;
            }
            set
            {
                this.mCreatedBy = value;
            }
        }
        
        public byte[] RowVersion
        {
            get
            {
                return this.mRowVersion;
            }
            set
            {
                this.mRowVersion = value;
            }
        }
        
        public static Percolator ToPercolator(PercolatorWeb percolator)
        {
            Percolator result = new Percolator();
            result.Id = percolator.Id;
            result.Bundle = percolator.BundleId;
            result.Name = percolator.Name;
            result.Description = percolator.Description;
            result.Type = percolator.Type;
            result.Severity = percolator.Severity;
            result.Query = percolator.Query;
            result.IssueType = percolator.IssueType;
            result.Resource = percolator.Resource;
            result.Response = percolator.Response;
            result.Responder = percolator.Responder;
            result.Visualization = percolator.Visualization;
            result.MatchAll = percolator.MatchAll;
            result.ImplementationNotes = percolator.ImplementationNotes;
            result.CreatedDate = percolator.CreatedDate;
            result.LastModifiedDate = percolator.LastModifiedDate;
            result.LastModifiedBy = percolator.LastModifiedBy;
            result.CreatedBy = percolator.CreatedBy;
            result.RowVersion = percolator.RowVersion;
            return result;
        }
        
        public static PercolatorWeb ToPercolatorWeb(Percolator percolator)
        {
            PercolatorWeb result = new PercolatorWeb();
            result.Id = percolator.Id;
            result.BundleId = percolator.Bundle;
            result.Name = percolator.Name;
            result.Description = percolator.Description;
            result.Type = percolator.Type;
            result.Severity = percolator.Severity;
            result.Query = percolator.Query;
            result.IssueType = percolator.IssueType;
            result.Resource = percolator.Resource;
            result.Response = percolator.Response;
            result.Responder = percolator.Responder;
            result.Visualization = percolator.Visualization;
            result.MatchAll = percolator.MatchAll;
            result.ImplementationNotes = percolator.ImplementationNotes;
            result.CreatedDate = percolator.CreatedDate;
            result.LastModifiedDate = percolator.LastModifiedDate;
            result.LastModifiedBy = percolator.LastModifiedBy;
            result.CreatedBy = percolator.CreatedBy;
            result.RowVersion = percolator.RowVersion;
            return result;
        }
    }

}
