//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Monitoring
{
    public partial class ProbeWeb
    {
        
        private string mId;
        
        private string mBundleId;
        
        private string mName;
        
        private string mDescription;
        
        private string mProvider;
        
        private System.Collections.Generic.IDictionary<string, object> mParameters;
        
        private System.Collections.Generic.IDictionary<string, Avanade.Amp.Core.Common.PropertyMetadata> mProperties;
        
        private string mCrontab;
        
        private bool mDiscard;
        
        private string mFilter;
        
        private System.Nullable<System.DateTime> mCreatedDate;
        
        private System.Nullable<System.DateTime> mLastModifiedDate;
        
        private string mLastModifiedBy;
        
        private string mCreatedBy;
        
        private byte[] mRowVersion;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Provider
        {
            get
            {
                return this.mProvider;
            }
            set
            {
                this.mProvider = value;
            }
        }
        
        public System.Collections.Generic.IDictionary<string, object> Parameters
        {
            get
            {
                return this.mParameters;
            }
            set
            {
                this.mParameters = value;
            }
        }
        
        public System.Collections.Generic.IDictionary<string, Avanade.Amp.Core.Common.PropertyMetadata> Properties
        {
            get
            {
                return this.mProperties;
            }
            set
            {
                this.mProperties = value;
            }
        }
        
        public string Crontab
        {
            get
            {
                return this.mCrontab;
            }
            set
            {
                this.mCrontab = value;
            }
        }
        
        public bool Discard
        {
            get
            {
                return this.mDiscard;
            }
            set
            {
                this.mDiscard = value;
            }
        }
        
        public string Filter
        {
            get
            {
                return this.mFilter;
            }
            set
            {
                this.mFilter = value;
            }
        }
        
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.mCreatedDate;
            }
            set
            {
                this.mCreatedDate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastModifiedDate
        {
            get
            {
                return this.mLastModifiedDate;
            }
            set
            {
                this.mLastModifiedDate = value;
            }
        }
        
        public string LastModifiedBy
        {
            get
            {
                return this.mLastModifiedBy;
            }
            set
            {
                this.mLastModifiedBy = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.mCreatedBy;
            }
            set
            {
                this.mCreatedBy = value;
            }
        }
        
        public byte[] RowVersion
        {
            get
            {
                return this.mRowVersion;
            }
            set
            {
                this.mRowVersion = value;
            }
        }
        
        public static Probe ToProbe(ProbeWeb probe)
        {
            Probe result = new Probe();
            result.Id = probe.Id;
            result.BundleId = probe.BundleId;
            result.Name = probe.Name;
            result.Description = probe.Description;
            result.Provider = probe.Provider;
            result.Parameters = probe.Parameters;
            result.Properties = probe.Properties;
            result.Crontab = probe.Crontab;
            result.Discard = probe.Discard;
            result.Filter = probe.Filter;
            result.CreatedDate = probe.CreatedDate;
            result.LastModifiedDate = probe.LastModifiedDate;
            result.LastModifiedBy = probe.LastModifiedBy;
            result.CreatedBy = probe.CreatedBy;
            result.RowVersion = probe.RowVersion;
            return result;
        }
        
        public static ProbeWeb ToProbeWeb(Probe probe)
        {
            ProbeWeb result = new ProbeWeb();
            result.Id = probe.Id;
            result.BundleId = probe.BundleId;
            result.Name = probe.Name;
            result.Description = probe.Description;
            result.Provider = probe.Provider;
            result.Parameters = probe.Parameters;
            result.Properties = probe.Properties;
            result.Crontab = probe.Crontab;
            result.Discard = probe.Discard;
            result.Filter = probe.Filter;
            result.CreatedDate = probe.CreatedDate;
            result.LastModifiedDate = probe.LastModifiedDate;
            result.LastModifiedBy = probe.LastModifiedBy;
            result.CreatedBy = probe.CreatedBy;
            result.RowVersion = probe.RowVersion;
            return result;
        }
    }
}
