//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Monitoring
{
    public partial class ScheduleWeb
    {
        
        private string mId;
        
        private string mBundleId;
        
        private string mTargetId;
        
        private string mSiteId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public string TargetId
        {
            get
            {
                return this.mTargetId;
            }
            set
            {
                this.mTargetId = value;
            }
        }
        
        public string SiteId
        {
            get
            {
                return this.mSiteId;
            }
            set
            {
                this.mSiteId = value;
            }
        }
        
        public static Schedule ToSchedule(ScheduleWeb schedule)
        {
            Schedule result = new Schedule();
            result.Id = schedule.Id;
            result.BundleId = schedule.BundleId;
            result.TargetId = schedule.TargetId;
            result.SiteId = schedule.SiteId;
            return result;
        }
        
        public static ScheduleWeb ToScheduleWeb(Schedule schedule)
        {
            ScheduleWeb result = new ScheduleWeb();
            result.Id = schedule.Id;
            result.BundleId = schedule.BundleId;
            result.TargetId = schedule.TargetId;
            result.SiteId = schedule.SiteId;
            return result;
        }
    }
}
