//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Monitoring
{
    public partial class TriggerWeb
    {
        
        private string mId;
        
        private string mBundleId;
        
        private string mName;
        
        private string mDescription;
        
        private string mType;
        
        private string mCrontab;
        
        private System.Nullable<int> mSeverity;
        
        private string mQuery;
        
        private string mIssueScript;
        
        private string mIssueType;
        
        private string mResource;
        
        private string mResponse;
        
        private string mResponder;
        
        private string mVisualization;
        
        private string mImplementationNotes;
        
        private System.Nullable<System.DateTime> mCreatedDate;
        
        private System.Nullable<System.DateTime> mLastModifiedDate;
        
        private string mLastModifiedBy;
        
        private string mCreatedBy;
        
        private byte[] mRowVersion;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string BundleId
        {
            get
            {
                return this.mBundleId;
            }
            set
            {
                this.mBundleId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public string Description
        {
            get
            {
                return this.mDescription;
            }
            set
            {
                this.mDescription = value;
            }
        }
        
        public string Type
        {
            get
            {
                return this.mType;
            }
            set
            {
                this.mType = value;
            }
        }
        
        public string Crontab
        {
            get
            {
                return this.mCrontab;
            }
            set
            {
                this.mCrontab = value;
            }
        }
        
        public System.Nullable<int> Severity
        {
            get
            {
                return this.mSeverity;
            }
            set
            {
                this.mSeverity = value;
            }
        }
        
        public string Query
        {
            get
            {
                return this.mQuery;
            }
            set
            {
                this.mQuery = value;
            }
        }
        
        public string IssueScript
        {
            get
            {
                return this.mIssueScript;
            }
            set
            {
                this.mIssueScript = value;
            }
        }
        
        public string IssueType
        {
            get
            {
                return this.mIssueType;
            }
            set
            {
                this.mIssueType = value;
            }
        }
        
        public string Resource
        {
            get
            {
                return this.mResource;
            }
            set
            {
                this.mResource = value;
            }
        }
        
        public string Response
        {
            get
            {
                return this.mResponse;
            }
            set
            {
                this.mResponse = value;
            }
        }
        
        public string Responder
        {
            get
            {
                return this.mResponder;
            }
            set
            {
                this.mResponder = value;
            }
        }
        
        public string Visualization
        {
            get
            {
                return this.mVisualization;
            }
            set
            {
                this.mVisualization = value;
            }
        }
        
        public string ImplementationNotes
        {
            get
            {
                return this.mImplementationNotes;
            }
            set
            {
                this.mImplementationNotes = value;
            }
        }
        
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.mCreatedDate;
            }
            set
            {
                this.mCreatedDate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastModifiedDate
        {
            get
            {
                return this.mLastModifiedDate;
            }
            set
            {
                this.mLastModifiedDate = value;
            }
        }
        
        public string LastModifiedBy
        {
            get
            {
                return this.mLastModifiedBy;
            }
            set
            {
                this.mLastModifiedBy = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.mCreatedBy;
            }
            set
            {
                this.mCreatedBy = value;
            }
        }
        
        public byte[] RowVersion
        {
            get
            {
                return this.mRowVersion;
            }
            set
            {
                this.mRowVersion = value;
            }
        }
        
        public static Trigger ToTrigger(TriggerWeb trigger)
        {
            Trigger result = new Trigger();
            result.Id = trigger.Id;
            result.Bundle = trigger.BundleId;
            result.Name = trigger.Name;
            result.Description = trigger.Description;
            result.Type = trigger.Type;
            result.Crontab = trigger.Crontab;
            result.Severity = trigger.Severity;
            result.Query = trigger.Query;
            result.IssueScript = trigger.IssueScript;
            result.IssueType = trigger.IssueType;
            result.Resource = trigger.Resource;
            result.Response = trigger.Response;
            result.Responder = trigger.Responder;
            result.Visualization = trigger.Visualization;
            result.ImplementationNotes = trigger.ImplementationNotes;
            result.CreatedDate = trigger.CreatedDate;
            result.LastModifiedDate = trigger.LastModifiedDate;
            result.LastModifiedBy = trigger.LastModifiedBy;
            result.CreatedBy = trigger.CreatedBy;
            result.RowVersion = trigger.RowVersion;
            return result;
        }
        
        public static TriggerWeb ToTriggerWeb(Trigger trigger)
        {
            TriggerWeb result = new TriggerWeb();
            result.Id = trigger.Id;
            result.BundleId = trigger.Bundle;
            result.Name = trigger.Name;
            result.Description = trigger.Description;
            result.Type = trigger.Type;
            result.Crontab = trigger.Crontab;
            result.Severity = trigger.Severity;
            result.Query = trigger.Query;
            result.IssueScript = trigger.IssueScript;
            result.IssueType = trigger.IssueType;
            result.Resource = trigger.Resource;
            result.Response = trigger.Response;
            result.Responder = trigger.Responder;
            result.Visualization = trigger.Visualization;
            result.ImplementationNotes = trigger.ImplementationNotes;
            result.CreatedDate = trigger.CreatedDate;
            result.LastModifiedDate = trigger.LastModifiedDate;
            result.LastModifiedBy = trigger.LastModifiedBy;
            result.CreatedBy = trigger.CreatedBy;
            result.RowVersion = trigger.RowVersion;
            return result;
        }
    }
}
