//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.Hub
{
    
    
    public partial class ChannelWeb
    {
        
        private string mId;
        
        private string mName;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this.mName;
            }
            set
            {
                this.mName = value;
            }
        }
        
        public static Channel ToChannel(ChannelWeb channel)
        {
            Channel result = new Channel();
            result.Id = channel.Id;
            result.Name = channel.Name;
            return result;
        }
        
        public static ChannelWeb ToChannelWeb(Channel channel)
        {
            ChannelWeb result = new ChannelWeb();
            result.Id = channel.Id;
            result.Name = channel.Name;
            return result;
        }
    }
}
