//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.EntityAuditLog
{
    
    
    public partial class EntityAuditLogWeb
    {
        
        private string mId;
        
        private string mEntityId;
        
        private string mTableName;
        
        private string mAction;
        
        private string mUserIdentity;
        
        private string mColumnName;
        
        private string mNewValue;
        
        private string mOriginalValue;
        
        private System.DateTime mTimestamp;
        
        private string mEntityAuditCommentId;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string EntityId
        {
            get
            {
                return this.mEntityId;
            }
            set
            {
                this.mEntityId = value;
            }
        }
        
        public string TableName
        {
            get
            {
                return this.mTableName;
            }
            set
            {
                this.mTableName = value;
            }
        }
        
        public string Action
        {
            get
            {
                return this.mAction;
            }
            set
            {
                this.mAction = value;
            }
        }
        
        public string UserIdentity
        {
            get
            {
                return this.mUserIdentity;
            }
            set
            {
                this.mUserIdentity = value;
            }
        }
        
        public string ColumnName
        {
            get
            {
                return this.mColumnName;
            }
            set
            {
                this.mColumnName = value;
            }
        }
        
        public string NewValue
        {
            get
            {
                return this.mNewValue;
            }
            set
            {
                this.mNewValue = value;
            }
        }
        
        public string OriginalValue
        {
            get
            {
                return this.mOriginalValue;
            }
            set
            {
                this.mOriginalValue = value;
            }
        }
        
        public System.DateTime Timestamp
        {
            get
            {
                return this.mTimestamp;
            }
            set
            {
                this.mTimestamp = value;
            }
        }
        
        public string EntityAuditCommentId
        {
            get
            {
                return this.mEntityAuditCommentId;
            }
            set
            {
                this.mEntityAuditCommentId = value;
            }
        }
        
        public static EntityAuditLog ToEntityAuditLog(EntityAuditLogWeb entityAudit)
        {
            EntityAuditLog result = new EntityAuditLog();
            result.Id = entityAudit.Id;
            result.EntityId = entityAudit.EntityId;
            result.TableName = entityAudit.TableName;
            result.Action = entityAudit.Action;
            result.UserIdentity = entityAudit.UserIdentity;
            result.ColumnName = entityAudit.ColumnName;
            result.NewValue = entityAudit.NewValue;
            result.OriginalValue = entityAudit.OriginalValue;
            result.Timestamp = entityAudit.Timestamp;
            result.EntityAuditCommentId = entityAudit.EntityAuditCommentId;
            return result;
        }
        
        public static EntityAuditLogWeb ToEntityAuditLogWeb(EntityAuditLog entityAudit)
        {
            EntityAuditLogWeb result = new EntityAuditLogWeb();
            result.Id = entityAudit.Id;
            result.EntityId = entityAudit.EntityId;
            result.TableName = entityAudit.TableName;
            result.Action = entityAudit.Action;
            result.UserIdentity = entityAudit.UserIdentity;
            result.ColumnName = entityAudit.ColumnName;
            result.NewValue = entityAudit.NewValue;
            result.OriginalValue = entityAudit.OriginalValue;
            result.Timestamp = entityAudit.Timestamp;
            result.EntityAuditCommentId = entityAudit.EntityAuditCommentId;
            return result;
        }
    }
}
