//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanade.Amp.Core.EntityAuditLog
{
    public partial class EntityAuditCommentWeb
    {
        private string mId;
        private string mComment;
        
        public string Id
        {
            get
            {
                return this.mId;
            }
            set
            {
                this.mId = value;
            }
        }
        
        public string Comment
        {
            get
            {
                return this.mComment;
            }
            set
            {
                this.mComment = value;
            }
        }
        
        public static EntityAuditComment ToEntityAuditComment(EntityAuditCommentWeb entityAuditComment)
        {
            EntityAuditComment result = new EntityAuditComment();
            result.Id = entityAuditComment.Id;
            result.Comment = entityAuditComment.Comment;
            return result;
        }
        
        public static EntityAuditCommentWeb ToEntityAuditCommentWeb(EntityAuditComment entityAuditComment)
        {
            EntityAuditCommentWeb result = new EntityAuditCommentWeb();
            result.Id = entityAuditComment.Id;
            result.Comment = entityAuditComment.Comment;
            return result;
        }
    }
}
